---
title: "About"
---

A fundamental mode of human existence in our modern day world is that vast, vast majority of people trade their labor for money and other means of sustaining their lives. Our lives depend on human labor having value. In contrast, capitalists sustain themselves by owning things and extracting the fruits of other people's labor via their control and ownership of shelter along with the means of producing and transporting food, water, energy, and information. The power of ownership has historically been balanced by the power of people to collectively withhold their labor and when push really came to shove, the capacity of violence of laborers is greater than that of capitalists.

In this decade of the 2020's, technology that can contend for the label "Artificial General Intelligence" (AGI) has arrived. As of writing this, it is largely constrained to text, image, video generation, and other business specific data domains. I am going shortcut a debate about AGI's exact capabilities, labor replacement versus the creation of new forms of labor, etc. and simply state my belief. This kind of technology will transfer into a robotic embodiment capable of replacing human labor in the physical domain in addition to the information domain, that once this happens the value of human labor will plummet, and along with it the quality and continuation of our lives. This robotic embodiment will also be the final piece needed to flip the dynamic of violence capacity into the hands of capitalists. This begs the question: what will become of us once this comes to pass? I find it unlikely the owners and controllers of this technology will create a utopia for the rest of us. I believe they will simply continue to follow the same mode of operation they follow today; acquire and exercise as much power as they can.

Labor (you, me, and almost certainly everyone else you know) needs to gain collective control and ownership of this technology before our ability to do so is stripped from us (notice that the elite of the United States and China are currently engaged in a similar struggle with each other right now).

Thus, this idea, this thing "Left Robotics" to answer the question of where do you start? For me, the starting line is a collective, a cooperative that creates software and hardware for robotics that is held in common, where the fruits of the productivity of the technology are enjoyed by the laborers in the group and the people in the community they exist in.

leftrobotics@proton.me

[https://github.com/Mark-Yeatman/left-robotics](https://github.com/Mark-Yeatman/left-robotics)